### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by gvmelle**
I added the Dutch (nl_NL) translation. CDATA not (yet) translated.

### CODE REVIEW

**Comment by Grunthos** [comment]
Hi, once again, I'm almost ready to go live with a new version...and I've added a few more strings....any chance you could do an update ;-)?

Also...any chance you could send me your email address (via email)?

**Comment by gvmelle** [comment]
Yes, there is a change ;-)

My email address is: gvmelle@gmail.com

ciao,

Gideon

On Thursday, October 22, 2015, Grunthos <notifications@github.com> wrote:

> Hi, once again, I'm almost ready to go live with a new version...and I've
> added a few more strings....any chance you could do an update ;-)?
>
> Also...any chance you could send me your email address (via email)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eleybourn/Book-Catalogue/pull/541#issuecomment-150176972>
> .
>


-- 
Ciao,

Gideon

~~o
<#\,
()/()

**Comment by Grunthos** [comment]
Thank you!

I also removed your email address from the previous message.

**Comment by gvmelle** [comment]
I now see an update 520, but the text is partly the same as update 513 that
is still in my fork. I left it that way and pasted the lines for update 520
underneath. all You spelled the name of the Greek translator as Dimitris
Klisiaris, and also in the acknowledgement as Dimitris Klisiari. I
corrected that in my fork for the Dutch translation.



Ciao,

Gideon

~~o
<#\,
()/()

**Comment by gvmelle** [comment]
I guess 5.1.3 has been replaced by 5.2.0

Ciao,

Gideon

~~o
<#\,
()/()

**Comment by Grunthos** [comment]
On 22/10/2015 10:54 PM, Gideon van Melle wrote:
> I guess 5.1.3 has been replaced by 5.2.0

Yeah, trying to bump minor version number for feature changes. There's not much 
in this release, but there is a new feature and I'd like to make a release to 
get some old change into the world.

**Pull request merged**
