### PR TITLE
Spanish 5.1.1

### PR DESCRIPTION
**Pull request by jgaldo**
Updated Spanish translation for version 5.1.1.

### CODE REVIEW

**Comment by jgaldo** [comment]
Hi, Today update crashes when starting in my mobile (Samsung with Android
4.2.2), and there is a comment in Play Store saying the same. I have sent
the system report but I do not know who receives it.

Is the update final 5.1.1 or still beta?
O Dec 31, 2014 1:02 AM, "Grunthos" <notifications@github.com> escribiu:

**Comment by Grunthos** [comment]
Hi,

I am reverting to a previous version; something went wrong in the build process. 
Please send any error logs vi "Help"->"Send Information".

Thanks,

Philip Warner

**Comment by jgaldo** [comment]
Hi,

I have just made a change in the Spanish translation for 5.1.1.

And one more thing: in the definition of the new styles there are "nulls"
in two of them (second and third, starting by the end). I thought it was a
problem with the translation, but they appear also in English (see attached
screenshot).

Regards,

Jose
O Jan 2, 2015 11:26 AM, "Grunthos" <notifications@github.com> escribiu:

**Comment by Grunthos** [comment]
Any chance you could email the image or share it via other means, because they don't make it into GitHub,

**Pull request merged**
