### PR TITLE
Greek translation

### PR DESCRIPTION
**Pull request by dklisiaris**
I 've added greek translation.

### CODE REVIEW

**Comment by Grunthos** [comment]
Thank you! Im sorry I didnt see this. Will incorporate in next release. How should it be attributed? We would normally say "...Greek (dklisiaris)", but can easily use a real name.

**Comment by dklisiaris** [comment]
Its ok. You can use my real name which is: Dimitris Klisiaris

**Comment by Grunthos** [comment]
Hi, almost ready to go live with this version...but I've added a few more strings....any chance you could do an update ;-)?

Also...any chance you could send me your email address (via email)?

**Comment by dklisiaris** [comment]
Hi there! I'll do an update. You can mail me at dklisiaris@gmail.com

**Pull request merged**
