### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by glha**
Translation to pt-br

### CODE REVIEW

**Comment by glha** [comment]
This commit has special html chars as `&ordm;` instead of º ([UTF-8, attached](https://github.com/eleybourn/Book-Catalogue/files/1264541/strings_ptBR.txt)), but when I tried one locazilation helper for android from xda, it complained about every & not being an entity. So, before I continue with the translation, which one is valid and if both are, which one is preferred? Thanks!

**Comment by Grunthos** [comment]
I am sorry, I am not sure what the question relates to: do we need to convert all bare "&" to &amp; ... I will look into it.

More generally, using the &<code>; escaping would be the correct thing to do.

Sorry I am not being vert helpful!

**Comment by Grunthos** [comment]
It should support any XML (or which HTML is a subset) entity. Sadly, just using UTF8 will produce errors.

Can you give an example of one of the strings it complained about?

**Comment by Grunthos** [comment]
For future reference, just typing the characters works, assuming UTF8

**Pull request merged**
