### PR TITLE
Add new pattern for serie : "serieName #number : bookName"

### PR DESCRIPTION
**Pull request by GuillaumeSmaha**
It's a new pattern to parse book in this format : "serieName #number : bookName".
For this case, the position (#number) must be different to null.

I also fix the NOTE to use the same pattern between findSeries and cleanupSeriesPosition.

### CODE REVIEW

**Comment by Grunthos** [comment]
Looking at this one now; it looks a little complex in the code is duplicated in several places. This probably means that our base code is badly designed (quite possible), or your base code needs to be centralised somehow.

Still trying to work out what is going on here...

**Comment by Grunthos** [comment]
My initial thinking is that 'findSeries()' should be modified to return both the title and the series rather than messing with the character positions in each piece of code.

**Comment by Grunthos** [comment]
Also, it looks like the spacing in some of the files has been changed, which makes github diffs harder to use (AFAICT). It's good to cleanup files, but it's nice to do that outside of the code patching cycle.

**Comment by Grunthos** [comment]
OK...looked more closely, and I do think this would be better implemented by:

- changing SeriesDetails to add 'String title' and REMOVE startChar and position (at least to highlight errors and prevent people using them)
-  modify 'findSeries()' to do the whole job
- then change the code elsewhere as necessary (which should be much simpler)

Is this something you mind doing?

P.S. And I should have said: THANKS for doing this! I may not *sound* grateful when I just criticize a patch, but I am. Anything that improves BC is great. I just need to protect myself from maintenance headaches.

**Comment by GuillaumeSmaha** [comment]
Hi ! 
Good idea for the new member: 'String title'.
It's better to do this.

Concerning the spacing, sorry but Android Study replace sometimes the tabulations by 4 spaces.
What do you think about using a coding style like K9 ? It's a plugin to manage indentation, ...
see https://github.com/k9mail/k-9/wiki/CodeStyle 
It may be better to use another branch to edit all sources.

I understand and accept your opinion ;)

**Comment by GuillaumeSmaha** [comment]
Here an example for the new pattern (ISBN-10) : 2811203400 : "La trilogie des Joyaux noirs, tome 1 : Fille du sang" 
http://www.amazon.fr/trilogie-Joyaux-noirs-Fille-sang/dp/2811203400/ref=sr_1_2?ie=UTF8&qid=1440070939&sr=8-2&keywords=La+trilogie+des+Joyaux

**Comment by Grunthos** [comment]
Looking at the new version, ISTM a title like:

- "Perspectives on Personality (7th Edition)"
or 
- "Something Silly (An Unuathorized Biography)"

will be incorrectly identified as books in a series.

I could be misreading the code...but my first impression is that you need to be much more restrictive on your matching.

Also, since we now get the title from this routine, returning 'null' is no longer an option.

**Comment by GuillaumeSmaha** [comment]
For the book, "Perspectives on Personality (7th Edition)", this is the current pattern which made the mistake but I can fix it.
See https://github.com/eleybourn/Book-Catalogue/blob/master/src/com/eleybourn/bookcatalogue/Series.java#L166 , the name is defined and the position is optional.
It's possible to check if position is different of null to have a serie like the variable **needPosition**, but a book with this format "bookName (serieName)", the serie will be not parsed.
I think it's hard to kown if it is just "bookName" or "bookName (serieName)" and currently, I think it's a good way to parse "bookName (serieName)".

Concerning the new pattern "serieName #number : bookName", it's due to the empty text for the position pattern in **mSeriesNumberPrefixes**.
With

	private static final String mSeriesNumberPrefixes = "(#|number|num|num.|no|no.|nr|nr.|book|bk|bk.|volume|vol|vol.|tome|part|pt.)";

instead of

	private static final String mSeriesNumberPrefixes = "(#|number|num|num.|no|no.|nr|nr.|book|bk|bk.|volume|vol|vol.|tome|part|pt.|)";

, it's work.

What do you think, can we remove the empty text from the pattern ?
	
---

For the null value, what can I return instead of null ? just the title set without name and position ?

**Comment by Grunthos** [comment]
1. I don't think removing the empty string from the pattern is a good idea, except when parsing the format 'series-name series-pos: title'. I'd probably add 'needPositionPrefix', set it to true when a ':' is found, and use a different pattern.


2. Rather than returning null it should always make sure the title is filled in, but possibly return null in the series name. The final 'if' needs an else clause, and you need to make sure details.title is ALWAYS set to something value. Then ALL code that calls it needs to be updated so that 'if (details != null...' is replaced by 'if (details.name != null...' (and similar).


3. I'm pretty sure you shouldn't use lastIndexOf when looking for a ':'.

**Pull request closed without merging**
