### PR TITLE
Android stuidio support

### PR DESCRIPTION
**Pull request by silin**
Fixing of ticket: https://github.com/eleybourn/Book-Catalogue/issues/648
See BUILDING file for build details

### CODE REVIEW

**Comment by Grunthos** [comment]
Looking though this now, and I have some silly(?) questions that are probably more about Android Studio in general:

1. Where has ActionBarSherlock gone? I am used to seeing it as a separate project with sources etc, but now it only appears in "Structure->Libraries". Do we still need all the sources? I don't seem to be able to get to any of the sources.

2. I am used to seeing 'changed' files (according to git) in Eclipse (a little marker that says they are different to HEAD). Is this possible? 

3. Oddly, when I edit files I get no indicator that they are not saved (Eclipse has "*" next to the name, as does pretty much every other editor I use). Is this a feature I can turn on/off?

4. Editing strings: is there a tool to help me analyze which languages are missing strings? Eclipse didn't really have this (lint for language files didn't work for me in recent releases). Just curious.

That's about it for now!

The good news is that I can build it, at least! Nice work.

**Comment by Grunthos** [comment]
OK, I've answered (2)...they change colour, and there's a setting to see dirs that contain changed files.

**Comment by silin** [comment]
@Grunthos 
1) All libraries now are integrated by build.script. For Android Studio we don`t need external ActionBarSherlock dependency, because we  load it from central maven repository. See this line in build script:
   ```
        compile 'com.actionbarsherlock:actionbarsherlock:4.4.0@aar'
   ```
   Actually we can also remove most of libraries from 'libs' fodler and also replace them by maven links, but they are saved to be identical as for Eclipse project

3) Android Studio saves all changes immediately (by default as I know)
4) Open 'strings.xml' file. Then click 'Open editor' (See http://screencast.com/t/ntnDxjaOxn). You will see a table with all translations in one place

**Comment by Grunthos** [comment]
Thanks for this; makes sense. Given the two different approaches I suspect I should make sure ABS is the same for both, or standardize on Android Studio.

I have one more question: in Eclipse if I use a type in a method, eg.:

    Local loc;

If the type has not been imported, then Eclipse will suggest the import.

This does not seem to happen in Android Studio. Is there a shortcut or setting to do this?

**Comment by silin** [comment]
As I know autoimports are set by default. If not you can set this option manually. But most often I faced with such problems when I have alternatives for this class. In this case you have to manually select needed package (just set cursor to the fields and press Alt-Enter, then select desired package)

**Comment by Grunthos** [comment]
ty, again. Alt-Enter is good. I guess I need to read a basic intro to AS...

**Comment by Grunthos** [comment]
OK, this may not be the best place for gradle questions, and I hope I am not annoying you...but I have one more...

In Eclipse I use a custom keywstore for signing debug builds (I build on more than one machine, and like to use same keys).

In AS, I *can* change the keystore, but the changes go into build.gradle. Is there some way of having a "build.gradle.local" (or something like that) which will be included in the build process, but not added to git and not break the build for people who do not have the .local version?

**Comment by silin** [comment]
There are several options for this:

**Comment by Grunthos** [comment]
It's for running in debug, so just using build scripts would be simplest in the long term (I think!). Is is possible to create a build script that won't fail if the local file is missing?

**Comment by silin** [comment]
local.properties files is created automatically in recent versions of Android studio. Also you don`t need specifiy keystore for debug builds (why do you need this)? In case if you want to build apk with the same certificate to avoid uninstalling previous version (due to 'inconsistent certificates' error while installing new version by Android Studio), you just can to add your debug keystore to the repository. In this case all people can build debug versions with same certificates.

To reach this you need:
1. Create `keystore` folder in root project folder and place`debug.keysore` into it
2. In build.gradle add signing information. For this add next code in `android` closure:

    android {
        ...
        defaultConfig {
            ....
            signingConfig signingConfigs.debug
        }
        ...
        signingConfigs {
            debug {
                storeFile file('keystore/debug.keystore')
            }
        }
    }

3. `Sync project with Gradle` to apply changes

**Pull request merged**
