### PR TITLE
Add support to manage search order

### PR DESCRIPTION
**Pull request by GuillaumeSmaha**
I had an interface in Administration to choose the order for the research and to disable or enable a research.
I took for example the panel Bookstyle to create this interface.

### CODE REVIEW

**Comment by GuillaumeSmaha** [comment]
Thank for your return.

- I updated the comment

- It's already not possible to disable all providers
see https://github.com/eleybourn/Book-Catalogue/pull/685/files#diff-d45b9bb40fac99d65c1fe577bb7ee67dR150

- mMaxSearchBits is now static and final

- I move *idAssigned = new ArrayList<Integer>()* in **loadPreferredSearchOrder** to create an object for missing providers.
It permit to complete the list at the end with missing provider form user preference. Example : a update add a new provider.
So **generatePreferredSearchOrder** is more simple.

- Now, I will see for the research by Author/Title and for the ASINs

**Comment by Grunthos** [comment]
OK will wait until you are finished. In the mean time:

- why is providersEnabled stored as a String in preferences, rather than an Integer?

- in loadPreferredSearchOrder I'm pretty sure anything that is explicitly disabled by the user should not be added to the list by the last step. You may be better off saving a 'disabled' list rather than an 'enabled' list, then add all 'disabled' items to idAssigned. This will also future-proof us when we add new providers.

**Comment by GuillaumeSmaha** [comment]
Hi, I come back.
- I edited the SearchProvider to add the list of search supported (ISBN, ASIN and Title/Author). A message is drawed when there is none provider for a kind of search. So I edit SearchManager to use this new information.
- I fix the string preference to an integer.
- For loadPreferredSearchOrder, I check to add a new provider and it's work ;t he new provider appears in the list.

**Comment by GuillaumeSmaha** [comment]
@Grunthos I cleaned my commits and rebase all in one.

What do you think now ?

**Comment by Grunthos** [comment]
Sorry about not getting back sooner; will look again for next release after the coming bug fix

**Pull request closed without merging**
